name: midas
description: midas
publish_to: "none"
version: 1.0.0+1




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand.ttf
       


environment:
  sdk: ">=3.1.0 <17.0.0"



dependencies:
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2


  
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

