# Generated by Django 5.0.2 on 2024-03-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midas', '0003_alter_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategysite',
            name='site',
        ),
        migrations.RemoveField(
            model_name='strategysite',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategytoken',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='strategytoken',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tokens',
            name='user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='info',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='url',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='cellphone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.client'),
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='midas.client'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(to='midas.client'),
        ),
        migrations.AddField(
            model_name='site',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.client'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.client'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='sites',
            field=models.ManyToManyField(to='midas.site'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.commodity'),
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='midas.client')),
            ],
        ),
        migrations.AddField(
            model_name='strategy',
            name='tokens',
            field=models.ManyToManyField(to='midas.token'),
        ),
        migrations.DeleteModel(
            name='ClientGroup',
        ),
        migrations.DeleteModel(
            name='StrategySite',
        ),
        migrations.DeleteModel(
            name='StrategyToken',
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
